version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "8080:8080" # Map cổng của ứng dụng Vue.js
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000" # Map cổng của ứng dụng Node.js
